#!/usr/bin/env bash
Generating public/private rsa key pair.
My identification has been saved in school.
Myr public key has been saved in school.pub.
The key fingerprint is:
 ssh-keygen -t rsa -b 4096 -C "betty""

